[package]
name = "vtb-recorder"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vtb-common = { path = "../vtb-common" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true }
tracing.workspace = true
chrono.workspace = true
reqwest.workspace = true
async-trait = "0.1"

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "test-util"] }
tempfile = "3"
