//! Core domain types shared across the toolkit.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// A normalized danmaku (chat) message, platform-agnostic.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum LiveEvent {
    /// Plain chat message.
    Danmaku(DanmakuMsg),
    /// A paid message (SuperChat / 醒目留言).
    SuperChat(SuperChatMsg),
    /// Gift sent to the streamer.
    Gift(GiftMsg),
    /// Membership purchase (舰长/提督/总督 or channel membership).
    GuardBuy(GuardBuyMsg),
    /// Viewer entered the room.
    Enter(EnterMsg),
    /// Like / heartbeat style interactions.
    Like(LikeMsg),
    /// Live started.
    LiveStart { room_id: u64, timestamp: DateTime<Utc> },
    /// Live ended.
    LiveEnd { room_id: u64, timestamp: DateTime<Utc> },
    /// Watched-count / popularity update.
    WatchedChange { room_id: u64, count: u64 },
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct DanmakuMsg {
    pub room_id: u64,
    pub uid: u64,
    pub username: String,
    pub text: String,
    pub timestamp: DateTime<Utc>,
    /// Fan medal (粉丝牌) name and level, if worn.
    pub medal: Option<Medal>,
    /// Guard level: 0 none, 1 总督, 2 提督, 3 舰长.
    pub guard_level: u8,
    /// True if the sender is a room admin (房管).
    pub is_admin: bool,
    /// Emoticon URL if this danmaku is a sticker.
    pub emoticon: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Medal {
    pub name: String,
    pub level: u32,
    pub anchor_room_id: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct SuperChatMsg {
    pub room_id: u64,
    pub uid: u64,
    pub username: String,
    pub text: String,
    /// Price in CNY.
    pub price: f64,
    pub timestamp: DateTime<Utc>,
    pub duration_secs: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct GiftMsg {
    pub room_id: u64,
    pub uid: u64,
    pub username: String,
    pub gift_name: String,
    pub gift_id: u64,
    pub count: u64,
    /// Total value in CNY (0 for free gifts).
    pub total_price: f64,
    pub timestamp: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct GuardBuyMsg {
    pub room_id: u64,
    pub uid: u64,
    pub username: String,
    /// 1 总督, 2 提督, 3 舰长.
    pub guard_level: u8,
    pub count: u64,
    pub price: f64,
    pub timestamp: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct EnterMsg {
    pub room_id: u64,
    pub uid: u64,
    pub username: String,
    pub timestamp: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LikeMsg {
    pub room_id: u64,
    pub uid: u64,
    pub username: String,
    pub timestamp: DateTime<Utc>,
}

/// A transcript segment produced by ASR.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct TranscriptSegment {
    /// Start offset in milliseconds relative to stream/file start.
    pub start_ms: u64,
    /// End offset in milliseconds.
    pub end_ms: u64,
    pub text: String,
    /// BCP-47-ish language tag detected, e.g. "zh", "en", "ja".
    pub lang: Option<String>,
    /// Whether this segment is final (vs. a partial hypothesis).
    pub is_final: bool,
}

/// A translated segment aligned to a transcript segment.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct TranslatedSegment {
    pub start_ms: u64,
    pub end_ms: u64,
    pub source_text: String,
    pub translated_text: String,
    pub source_lang: Option<String>,
    pub target_lang: String,
}

/// A detected highlight window in a stream or recording.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Highlight {
    pub start_ms: u64,
    pub end_ms: u64,
    /// 0.0..=1.0 combined score.
    pub score: f64,
    /// Human-readable reason, e.g. "弹幕密度峰值 + 笑声".
    pub reason: String,
    /// Per-signal scores for transparency.
    pub signals: HighlightSignals,
    /// Suggested clip title, if generated by a model.
    pub title: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq)]
pub struct HighlightSignals {
    pub danmaku_density: Option<f64>,
    pub danmaku_sentiment: Option<f64>,
    pub audio_energy: Option<f64>,
    pub multimodal: Option<f64>,
}

/// Status of a monitored live room.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum LiveStatus {
    Offline,
    Live,
    /// Round: rebroadcast of past recordings (B站轮播).
    Round,
}
